export const properties = [
  {
    id: '2',
    name: 'Стандрат',
    description: 'Студия с терассой и бассейном',
    price: '150PRB/ночь',
    priceNumber: 150,
    rooms: 2,
    guests: 10,
    amenities: ['WiFi', 'Кондиционер', 'TV', 'Бассейн', 'Сауна (с доплатой)', 'Мангал', 'Парковочное место'],
    image: 'https://picsum.photos/300/200?random=2',
    photos: [
      require('../assets/standart/st1.png'),
      require('../assets/standart/st2.png'),
      require('../assets/standart/st3.png'),
      require('../assets/standart/st4.png'),
      require('../assets/standart/st5.png'),
      require('../assets/standart/st6.png'),
      require('../assets/standart/st7.png'),
      require('../assets/standart/st8.png'),
      require('../assets/standart/st1.png'),
    ],
  },
  {
    id: '1',
    name: 'Люкс апартамент',
    description: 'Полный комфорт, с видом на природу',
    price: '200PRB/ночь',
    priceNumber: 200,
    rooms: 10,
    guests: 20,
    amenities: ['WiFi', 'Кондиционер', 'TV', 'Кухня', 'Бассейн', 'Сауна (с доплатой)', 'Мангал', 'Парковочное место', 'Караоке', 'Большой зал'],
    image: 'https://picsum.photos/300/200?random=1',
    photos: [
      require('../assets/luks/st1.png'),
      require('../assets/luks/st2.png'),
      require('../assets/luks/st3.png'),
      require('../assets/luks/st4.png'),
      require('../assets/luks/st5.png'),
      require('../assets/luks/st6.png'),
      require('../assets/luks/st7.png'),
      require('../assets/luks/st8.png'),
      require('../assets/luks/st9.png'),
      require('../assets/luks/st10.png'),
      require('../assets/luks/st1.png'),
    ],
  },
  {
    id: '3',
    name: 'Задний двор',
    description: 'Открытая местность с бассейном и беседкой',
    price: '100PRB/день',
    priceNumber: 100,
    rooms: null,
    guests: 15,
    amenities: ['WiFi', 'Бассейн', 'Мангал', 'Парковочное место', 'Караоке', 'Холодильник', 'Беседка', 'Шезлонги', 'Зонты'],
    image: 'https://picsum.photos/300/200?random=3',
    photos: [
      require('../assets/zad/zd1.png'),
      require('../assets/zad/zd2.png'),
      require('../assets/zad/zd3.png'),
      require('../assets/zad/zd4.png'),
      require('../assets/zad/zd5.png'),
      require('../assets/zad/zd1.png'),
      require('../assets/zad/zd2.png'),
      require('../assets/zad/zd3.png'),
    ],
  },
  {
    id: '4',
    name: 'Вся территория',
    description: 'Полный комплекс со всеми удобствами',
    price: '500PRB/ночь',
    priceNumber: 500,
    rooms: 10,
    guests: 30,
    amenities: ['WiFi', 'Кондиционер', 'TV', 'Кухня', 'Бассейн', 'Сауна (с доплатой)', 'Мангал', 'Парковочное место', 'Караоке', 'Большой зал', 'Беседка', 'Шезлонги', 'Зонты', 'Холодильник'],
    image: 'https://picsum.photos/300/200?random=4',
    photos: [
      require('../assets/luks/st1.png'),
      require('../assets/luks/st2.png'),
      require('../assets/luks/st3.png'),
      require('../assets/luks/st4.png'),
      require('../assets/luks/st5.png'),
      require('../assets/luks/st6.png'),
      require('../assets/luks/st7.png'),
      require('../assets/luks/st8.png'),
      require('../assets/luks/st9.png'),
      require('../assets/luks/st10.png'),
      require('../assets/zad/zd1.png'),
      require('../assets/zad/zd2.png'),
      require('../assets/zad/zd3.png'),
      require('../assets/zad/zd4.png'),
      require('../assets/zad/zd5.png'),
    ],
  },
];
